CREATE TABLE POKEMON_ENTRENADOR(
    ID_POKEMON INT(5) ,
    ID_ENTRENADOR INT(5),
    NUM_POKEDEX INT(3),
	MOTE VARCHAR(20),
	VITALIDAD INT(5) NOT NULL,
    ATAQUE INT(4) NOT NULL,
    DEFENSA INT(4) NOT NULL,
    ATAQUE_ESP INT(5),
    DEFENSA_ESP INT(5),
    ESTAMINA INT(4) NOT NULL,
    VELOCIDAD INT(4) NOT NULL,
    NIVEL INT(3) NOT NULL DEFAULT 1,
    FERTILIDAD INT(4) DEFAULT 5,
    EXPERIENCIA INT(4) DEFAULT 0,
    EQUIPO INT(1)
    
    );
    
ALTER TABLE POKEMON_ENTRENADOR
    ADD CONSTRAINT ID_POKEMON_PK PRIMARY KEY(ID_POKEMON);

ALTER TABLE POKEMON_ENTRENADOR
	ADD CONSTRAINT EQUIPO_CK CHECK (EQUIPO IN (1,2,3) );
    
    
CREATE TABLE POKEDEX(
    NUM_POKEDEX INT(3),
    NOMBRE VARCHAR(25) NOT NULL,
    TIPO_1 VARCHAR(20) NOT NULL,
    TIPO_2 VARCHAR(20),
    IMAGEN VARCHAR(100),
    SONIDO VARCHAR(100)
    );
    
ALTER TABLE POKEDEX
	ADD CONSTRAINT NUM_POKEDEX_PK PRIMARY KEY (NUM_POKEDEX),
	ADD CONSTRAINT TIPO_1_CK CHECK (TIPO_1 IN('AGUA','FUEGO','PLANTA','VOLADOR','ELECTRICO','NORMAL',NULL));
ALTER TABLE POKEDEX
    ADD CONSTRAINT TIPO_2_CK CHECK (TIPO_2 IN('AGUA','FUEGO','PLANTA','VOLADOR','ELECTRICO','NORMAL',NULL));

CREATE TABLE ENTRENADOR(
    ID_ENTRENADOR INT(5),
    NOMBRE VARCHAR(25) NOT NULL,
    POKEMONEDAS INT(6)
    );
    
ALTER TABLE ENTRENADOR
    ADD CONSTRAINT ID_ENTRENADOR_PK PRIMARY KEY (ID_ENTRENADOR);
    
    
CREATE TABLE COMBATE(
    ID_COMBATE INT(4) NOT NULL,
    JUGADOR_ENTRENADOR INT(5),
    FECHA_HORA_COMBATE DATE,
    RIVAL_ENTRENADOR VARCHAR(25),
    GANADOR VARCHAR(25),
    POKEMON_KO_JUGADOR INT(2),
    POKEMON_KO_RIVAL INT(2)
    );
   
   
ALTER TABLE COMBATE
	ADD CONSTRAINT ID_COMBATE_PK PRIMARY KEY (ID_COMBATE);
  

CREATE TABLE MOVIMIENTO(
    ID_MOVIMIENTO INT(5)NOT NULL,
    NOMBRE_MOV VARCHAR(15) NOT NULL,
    NIVEL INT DEFAULT 1,
    TIPO VARCHAR(7) NOT NULL,
    ESTAMINA INT NOT NULL,
    POTENCIA INT,
    TIPO_ELEMENTO VARCHAR(15) NOT NULL,
    NUM_TURNOS INT(1) DEFAULT 1,
    ESTADO VARCHAR(15) ,
    MEJORA VARCHAR(15),
    CANT_MEJORA INT(2)
    );
    
ALTER TABLE MOVIMIENTO
    ADD CONSTRAINT ID_MOV_PK PRIMARY KEY (ID_MOVIMIENTO),
    ADD CONSTRAINT TIPO_ELEMENTO_CK CHECK (TIPO_ELEMENTO IN('AGUA','FUEGO','PLANTA','VOLADOR','ELECTRICO','NORMAL')),
    ADD CONSTRAINT ESTADO_CK CHECK (ESTADO IN('PARALIZADO','DORMIDO','QUEMADO','SIN_ESTADO'));

CREATE TABLE MOVIMIENTO_POKEMON(
    ID_MOVIMIENTO INT(5) NOT NULL,
    ID_POKEMON INT(5)NOT NULL,
    LISTA_MOV INT
    );
    
ALTER TABLE MOVIMIENTO_POKEMON
    ADD CONSTRAINT ID_MOV_POK_PK PRIMARY KEY (ID_MOVIMIENTO, ID_POKEMON),
    ADD CONSTRAINT LISTA_MOV_CK CHECK (LISTA_MOV IN(1,2));
    

CREATE TABLE TURNO(
    ID_COMBATE INT(4) NOT NULL,
	NUM_TURNO INT(2) NOT NULL,
    ATAQUE_ENTRENADOR VARCHAR(40),
    ATAQUE_RIVAL VARCHAR(40)
    );
    
ALTER TABLE TURNO 
    ADD CONSTRAINT NUM_TURNO_PK PRIMARY KEY (NUM_TURNO,ID_COMBATE),
	ADD CONSTRAINT ID_COMB_FK FOREIGN KEY (ID_COMBATE) REFERENCES COMBATE(ID_COMBATE);

ALTER TABLE COMBATE 
	ADD CONSTRAINT ID_ENTRENADOR_FK FOREIGN KEY (JUGADOR_ENTRENADOR) REFERENCES ENTRENADOR(ID_ENTRENADOR);
	
ALTER TABLE POKEMON_ENTRENADOR
	ADD CONSTRAINT ID_ENTRENA_FK FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID_ENTRENADOR),
	ADD CONSTRAINT NUM_POKEDEX_FK FOREIGN KEY (NUM_POKEDEX) REFERENCES POKEDEX(NUM_POKEDEX);
	
ALTER TABLE MOVIMIENTO_POKEMON 
	ADD CONSTRAINT ID_ENT_FK FOREIGN KEY (ID_MOVIMIENTO) REFERENCES MOVIMIENTO(ID_MOVIMIENTO),
	ADD CONSTRAINT ID_POK_FK FOREIGN KEY (ID_POKEMON) REFERENCES POKEMON_ENTRENADOR(ID_POKEMON);
	
	
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (1,'BULBASAUR','PLANTA',NULL,'imgPo/BULBASAUR');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (2,'IVISAUR','PLANTA',NULL,'imgPo/IVISAUR');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (3,'VENUSAUR','PLANTA',NULL,'imgPo/VENUSAUR');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (4,'CHARMANDER','FUEGO',NULL,'imgPo/CHARMANDER');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (5,'CHARMELEON','FUEGO',NULL,'imgPo/CHARMELEON');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (6,'CHARIZARD','FUEGO','VOLADOR','imgPo/CHARIZARD');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (7,'SQUIRTLE','AGUA',NULL,'imgPo/SQUIRTLE');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (8,'WARTORTLE','AGUA',NULL,'imgPo/WARTORTLE');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (9,'BLASTOISE','AGUA',NULL,'imgPo/BLASTOISE');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (10,'PIDGEY','NORMAL','VOLADOR','imgPo/PIDGEY');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (11,'PIDGEOTTO','NORMAL','VOLADOR','imgPo/PIDGEOTTO');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (12,'PIDGEOT','NORMAL','VOLADOR','imgPo/PIDGEOT');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (13,'RATTATA','NORMAL',NULL,'imgPo/RATTATA');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (14,'RATICATE','NORMAL',NULL,'imgPo/RATICATE');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (15,'SPEAROW','NORMAL','VOLADOR','imgPo/SPEAROW');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (16,'FEAROW','NORMAL','VOLADOR','imgPo/FEAROW');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (17,'PIKACHU','ELECTRICO',NULL,'imgPo/PIKACHU');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (18,'RAICHU','ELECTRICO',NULL,'imgPo/RAICHU');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (19,'VULPIX','FUEGO',NULL,'imgPo/VULPIX');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (20,'NINETALES','FUEGO',NULL,'imgPo/NINETALES');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (21,'ODDISH','PLANTA',NULL,'imgPo/ODDISH');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (22,'GLOOM','PLANTA',NULL,'imgPo/GLOOM');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (23,'VILEPLUME','PLANTA',NULL,'imgPo/VILEPLUME');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (24,'PSYDUCK','AGUA',NULL,'imgPo/PSYDUCK');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (25,'GOLDUCK','AGUA',NULL,'imgPo/GOLDUCK');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (26,'GROWLITHE','FUEGO',NULL,'imgPo/GROWLITHE');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (27,'ARCANINE','FUEGO',NULL,'imgPo/ARCANINE');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (28,'POLIWAG','AGUA',NULL,'imgPo/POLIWAG');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (29,'POLIWHIRL','AGUA',NULL,'imgPo/POLIWHIRL');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (30,'POLIWRATH','AGUA',NULL,'imgPo/POLIWRATH');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (31,'PONYTA','FUEGO',NULL,'imgPo/PONYTA');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (32,'RAPIDASH','FUEGO',NULL,'imgPo/RAPIDASH');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (33,'MAGNEMITE','ELECTRICO',NULL,'imgPo/MAGNEMITE');
INSERT INTO POKEDEX (NUM_POKEDEX,NOMBRE,TIPO_1,TIPO_2,IMAGEN) VALUES (34,'MAGNETON','ELECTRICO',NULL,'imgPo/MAGNETON');

INSERT INTO ENTRENADOR (ID_ENTRENADOR,NOMBRE,POKEMONEDAS) VALUES (1,'JOSETI',1900);
INSERT INTO ENTRENADOR (ID_ENTRENADOR,NOMBRE,POKEMONEDAS) VALUES (2,'CHEMA',1200);
INSERT INTO ENTRENADOR (ID_ENTRENADOR,NOMBRE,POKEMONEDAS) VALUES (3,'LUIS',1000);
INSERT INTO ENTRENADOR (ID_ENTRENADOR,NOMBRE,POKEMONEDAS) VALUES (4,'PACO',1500);
INSERT INTO ENTRENADOR (ID_ENTRENADOR,NOMBRE,POKEMONEDAS) VALUES (5,'ANTONIO',1700);
INSERT INTO ENTRENADOR (ID_ENTRENADOR,NOMBRE,POKEMONEDAS) VALUES (6,'ALVARO',1400);

INSERT INTO POKEMON_ENTRENADOR (ID_POKEMON,ID_ENTRENADOR,NUM_POKEDEX,MOTE,VITALIDAD,ATAQUE,DEFENSA,ATAQUE_ESP,DEFENSA_ESP,ESTAMINA,VELOCIDAD,NIVEL,FERTILIDAD,ESTAMINA,EQUIPO)
						VALUES (1,1,1,"MANOLITO",30,24,21,20,30,10,30,DEFAULT,DEFAULT,DEFAULT,1);
INSERT INTO POKEMON_ENTRENADOR (ID_POKEMON,ID_ENTRENADOR,NUM_POKEDEX,MOTE,VITALIDAD,ATAQUE,DEFENSA,ATAQUE_ESP,DEFENSA_ESP,ESTAMINA,VELOCIDAD,NIVEL,FERTILIDAD,ESTAMINA,EQUIPO)
						VALUES (2,2,15,"ALFREDO",32,21,20,226,25,15,26,DEFAULT,DEFAULT,DEFAULT,1);

INSERT INTO MOVIMIENTO (ID_MOVIMIENTO,NOMBRE_MOV,NIVEL,TIPO,ESTAMINA,POTENCIA,TIPO_ELEMENTO,NUM_TURNOS,ESTADO,MEJORA,CANT_MEJORA)
				VALUES (1,'DORMIR',7,'ESTADO',6,NULL,'PLANTA',DEFAULT,'DORMIDO',NULL,NULL);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO,NOMBRE_MOV,NIVEL,TIPO,ESTAMINA,POTENCIA,TIPO_ELEMENTO,NUM_TURNOS,ESTADO,MEJORA,CANT_MEJORA)
				VALUES (2,'PARALIZAR',7,'ESTADO',6,4,'PLANTA',DEFAULT,'PARALIZADO',NULL,NULL);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO,NOMBRE_MOV,NIVEL,TIPO,ESTAMINA,POTENCIA,TIPO_ELEMENTO,NUM_TURNOS,ESTADO,MEJORA,CANT_MEJORA)
				VALUES (3,'QUEMAR',7,'ESTADO',6,3,'PLANTA',2,'QUEMADO',NULL,NULL);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO,NOMBRE_MOV,NIVEL,TIPO,ESTAMINA,POTENCIA,TIPO_ELEMENTO,NUM_TURNOS,ESTADO,MEJORA,CANT_MEJORA)
				VALUES (4,'MEJORAAGUA',1,'MEJORA',5,NULL,'AGUA',DEFAULT,'SIN_ESTADO','DEFENSA',1.2);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO,NOMBRE_MOV,NIVEL,TIPO,ESTAMINA,POTENCIA,TIPO_ELEMENTO,NUM_TURNOS,ESTADO,MEJORA,CANT_MEJORA)
				VALUES (5,'MEJORAFUEGO',1,'MEJORA',5,NULL,'FUEGO',DEFAULT,'SIN_ESTADO','ATAQUE',1.3);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO,NOMBRE_MOV,NIVEL,TIPO,ESTAMINA,POTENCIA,TIPO_ELEMENTO,NUM_TURNOS,ESTADO,MEJORA,CANT_MEJORA)
				VALUES (6,'MEJORAPLANTA',1,'MEJORA',5,NULL,'PLANTA',DEFAULT,'SIN_ESTADO','VITALIDAD',50);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO,NOMBRE_MOV,NIVEL,TIPO,ESTAMINA,POTENCIA,TIPO_ELEMENTO,NUM_TURNOS,ESTADO,MEJORA,CANT_MEJORA)
				VALUES (7,'MEJORAVOLADOR',1,'MEJORA',5,NULL,'VOLADOR',DEFAULT,'SIN_ESTADO','ATAQUE_ESP',1.4);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO,NOMBRE_MOV,NIVEL,TIPO,ESTAMINA,POTENCIA,TIPO_ELEMENTO,NUM_TURNOS,ESTADO,MEJORA,CANT_MEJORA)
				VALUES (8,'MEJORAELECTRICO',1,'MEJORA',5,NULL,'ELECTRICO',DEFAULT,'SIN_ESTADO','DEFENSA_ESP',1.5);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO,NOMBRE_MOV,NIVEL,TIPO,ESTAMINA,POTENCIA,TIPO_ELEMENTO,NUM_TURNOS,ESTADO,MEJORA,CANT_MEJORA)
				VALUES (9,'MEJORANORMAL',1,'MEJORA',5,NULL,'NORMAL',DEFAULT,'SIN_ESTADO','VELOCIDAD',1.05);